using ClaimsModule.Application.Common.Interfaces;
using ClaimsModule.Domain.Common;
using ClaimsModule.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace ClaimsModule.Persistence;

public class ClaimsDbContext : DbContext, IClaimsDbContext
{
    private readonly ICurrentUser? _currentUser;
    private readonly IDateTimeProvider? _clock;

    public ClaimsDbContext(DbContextOptions<ClaimsDbContext> options) : base(options) { }

    public ClaimsDbContext(DbContextOptions<ClaimsDbContext> options,
        ICurrentUser currentUser, IDateTimeProvider clock) : base(options)
    {
        _currentUser = currentUser;
        _clock = clock;
    }

    public DbSet<Claim> Claims => Set<Claim>();
    public DbSet<LossEvent> LossEvents => Set<LossEvent>();
    public DbSet<ClaimParty> ClaimParties => Set<ClaimParty>();
    public DbSet<ClaimRiskObject> ClaimRiskObjects => Set<ClaimRiskObject>();
    public DbSet<ClaimReserveComponent> ClaimReserveComponents => Set<ClaimReserveComponent>();
    public DbSet<ReserveHistory> ReserveHistories => Set<ReserveHistory>();
    public DbSet<ClaimDocument> ClaimDocuments => Set<ClaimDocument>();
    public DbSet<ClaimAuditLog> ClaimAuditLogs => Set<ClaimAuditLog>();
    public DbSet<CauseOfLossCode> CauseOfLossCodes => Set<CauseOfLossCode>();
    public DbSet<ClaimStatusTransition> ClaimStatusTransitions => Set<ClaimStatusTransition>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(ClaimsDbContext).Assembly);
        modelBuilder.HasSequence<long>("ClaimNumberSequence")
            .StartsAt(1)
            .IncrementsBy(1);

        // BaseEntity initialises Id to Guid.NewGuid() so the aggregate can wire up
        // child FKs immediately (e.g. ClaimAuditLog.ClaimId = Claim.Id). EF Core's
        // "value generated on add" detection treats a non-empty Id as a sign that
        // the entity already exists in the DB — which makes navigation-added rows
        // get UPDATEd instead of INSERTed. Keep the NEWSEQUENTIALID() column DEFAULT
        // (FRS Appendix A.4) but mark the property as never auto-generated by EF.
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            var pk = entityType.FindPrimaryKey();
            if (pk == null) continue;
            foreach (var property in pk.Properties)
            {
                if (property.ClrType == typeof(Guid))
                    property.ValueGenerated = Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never;
            }
        }

        var tenantId = _currentUser?.OrganizationId;
        if (tenantId.HasValue)
        {
            foreach (var entityType in modelBuilder.Model.GetEntityTypes())
            {
                if (typeof(BaseEntity).IsAssignableFrom(entityType.ClrType))
                {
                    var parameter = System.Linq.Expressions.Expression.Parameter(entityType.ClrType, "e");
                    var orgProp = System.Linq.Expressions.Expression.Property(parameter, nameof(BaseEntity.OrganizationEntityId));
                    var isDeletedProp = System.Linq.Expressions.Expression.Property(parameter, nameof(BaseEntity.IsDeleted));
                    var tenantValue = System.Linq.Expressions.Expression.Constant(tenantId.Value);
                    var falseValue = System.Linq.Expressions.Expression.Constant(false);
                    var tenantMatch = System.Linq.Expressions.Expression.Equal(orgProp, tenantValue);
                    var notDeleted = System.Linq.Expressions.Expression.Equal(isDeletedProp, falseValue);
                    var combined = System.Linq.Expressions.Expression.AndAlso(tenantMatch, notDeleted);
                    var lambda = System.Linq.Expressions.Expression.Lambda(combined, parameter);
                    modelBuilder.Entity(entityType.ClrType).HasQueryFilter(lambda);
                }
            }
        }
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        ApplyAuditAndTenant();
        return base.SaveChangesAsync(cancellationToken);
    }

    private void ApplyAuditAndTenant()
    {
        var now = _clock?.UtcNow ?? DateTimeOffset.UtcNow;
        var user = _currentUser?.UserId ?? "system";
        var tenant = _currentUser?.OrganizationId;

        foreach (var entry in ChangeTracker.Entries<BaseEntity>())
        {
            switch (entry.State)
            {
                case EntityState.Added:
                    if (entry.Entity.CreatedAt == default) entry.Entity.CreatedAt = now;
                    if (entry.Entity.UpdatedAt == default) entry.Entity.UpdatedAt = now;
                    if (string.IsNullOrEmpty(entry.Entity.UserCreated)) entry.Entity.UserCreated = user;
                    if (string.IsNullOrEmpty(entry.Entity.UserModified)) entry.Entity.UserModified = user;
                    if (entry.Entity.OrganizationEntityId == Guid.Empty && tenant.HasValue)
                        entry.Entity.OrganizationEntityId = tenant.Value;
                    break;
                case EntityState.Modified:
                    entry.Entity.UpdatedAt = now;
                    entry.Entity.UserModified = user;
                    break;
                case EntityState.Deleted:
                    entry.State = EntityState.Modified;
                    entry.Entity.IsDeleted = true;
                    entry.Entity.DeletedAt = now;
                    entry.Entity.UpdatedAt = now;
                    entry.Entity.UserModified = user;
                    break;
            }
        }
    }
}
